name: mini_pdf_epub_viewer
description: "A Flutter package for viewing PDF and EPUB documents from various sources (assets, files, network)."
version: 0.1.2
repository: https://github.com/Davies-K/mini_pdf_epub_viewer
homepage: https://github.com/davies-k
topics: ["pdf", "mini", "epub", "reader",]
funding: [https://buymeacoffee.com/davieskwarteng]

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  pdfx: ^2.8.0
  path_provider: ^2.1.5
  http: ^1.2.2
  epubx: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
